### ISSUE TITLE
M1

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [linebender/tiny-skia#38]
Is it safe to assume that tiny-skia is slower on Apples M1 chip due to lack of ARM NEON? Any idea on how much slower?

**Comment by RazrFalcon** [comment]
You can check it yourself: [arm64.html.zip](https://github.com/RazrFalcon/tiny-skia/files/7373295/arm64.html.zip) Just open this page in a browser. This is running on M1. Basically everything that requires f32x8 is slow, but other algorithms are pretty good.

Yes, it's not as fast as Skia, but rustc still does some autovectorization. So we still faster than Cairo, somehow.

Just to clarify, there is no NEON support because we're blocked by rust itself. It could be added as an unstable/nightly feature, if this is something you're interested in.

**Comment by CryZe** [comment]
They are actually about to finish adding all the NEON instructions into std. So stabilization might happen in the foreseeable future. I can do a PR with nightly NEON support before that.

**Comment by RazrFalcon** [comment]
@CryZe were can I follow the progress? 

Patches are welcome, since I don't really have much time lately.

**Comment by CryZe** [comment]
This is adding all the remaining instructions except a few that cause problems in LLVM: 
https://github.com/rust-lang/stdarch/pull/1230

**Comment by jeffreyrosenbluth** [comment]
Thanks, this is very helpful
